# nix/gen-buck-deps.nix
#
# Generates a Starlark file with Nix store paths for prebuilt_cxx_library.
# This avoids symlinks that break when store paths change.
#
# Usage (from flake): Automatically generated via nix-deps-bzl in flake.nix
# Usage (standalone): nix-build nix/gen-buck-deps.nix -o vendor/nix-deps.bzl
#
# The generated file contains variable assignments for each static library's
# paths. These are imported in vendor/BUCK and used with nix_prebuilt_cxx_library.
#
{
  pkgs ? import <nixpkgs> { },
  libmodern,
}:
let
  deps = import ./deps.nix {
    inherit pkgs libmodern;
  };
  s = deps.static;

  # Helper to get lib path (handles multi-output derivations)
  libPath = pkg: pkg.out or pkg;
  devPath = pkg: pkg.dev or pkg;

  # Generate the .bzl content
  content = ''
    # AUTO-GENERATED by nix/gen-buck-deps.nix
    # Do not edit manually. Regenerate with:
    #   nix-build nix/gen-buck-deps.nix -o third_party/nix-deps.bzl
    #
    # Nix store paths for static libraries (musl, no glibc).
    # Used by nix_prebuilt_cxx_library() in third_party/BUCK.

    # ════════════════════════════════════════════════════════════════════════════
    # BLAKE3 - fast cryptographic hash
    # ════════════════════════════════════════════════════════════════════════════
    # TODO[b7r6]: confirm TBB performance improvement
    BLAKE3_STATIC_LIB = "${libPath s.blake3-static}/lib/libblake3.a"
    BLAKE3_INCLUDE = "${devPath s.blake3-static}/include"

    # ════════════════════════════════════════════════════════════════════════════
    # LibreSSL - TLS/crypto (no OpenSSL)
    # ════════════════════════════════════════════════════════════════════════════
    LIBRESSL_CRYPTO_LIB = "${libPath s.libressl-static}/lib/libcrypto.a"
    LIBRESSL_SSL_LIB = "${libPath s.libressl-static}/lib/libssl.a"
    LIBRESSL_TLS_LIB = "${libPath s.libressl-static}/lib/libtls.a"
    LIBRESSL_INCLUDE = "${devPath s.libressl-static}/include"

    # ════════════════════════════════════════════════════════════════════════════
    # ada - WHATWG URL parser (vendored in third_party/ada, built with Buck2)
    # ════════════════════════════════════════════════════════════════════════════

    # ════════════════════════════════════════════════════════════════════════════
    # RE2 - fast regex
    # ════════════════════════════════════════════════════════════════════════════
    RE2_STATIC_LIB = "${libPath s.re2-static}/lib/libre2.a"
    RE2_INCLUDE = "${devPath s.re2-static}/include"

    # ════════════════════════════════════════════════════════════════════════════
    # Abseil - required by RE2
    # ════════════════════════════════════════════════════════════════════════════
    ABSEIL_INCLUDE = "${devPath s.abseil-static}/include"

    # ════════════════════════════════════════════════════════════════════════════
    # Catch2 - testing framework
    # ════════════════════════════════════════════════════════════════════════════
    CATCH2_STATIC_LIB = "${libPath s.catch2-static}/lib/libCatch2.a"
    CATCH2_MAIN_LIB = "${libPath s.catch2-static}/lib/libCatch2Main.a"
    CATCH2_INCLUDE = "${devPath s.catch2-static}/include"

    # ════════════════════════════════════════════════════════════════════════════
    # nanobench - microbenchmark framework
    # ════════════════════════════════════════════════════════════════════════════
    NANOBENCH_STATIC_LIB = "${libPath s.nanobench-static}/lib/libnanobench.a"
    NANOBENCH_INCLUDE = "${libPath s.nanobench-static}/include"

    # ════════════════════════════════════════════════════════════════════════════
    # rapidcheck - property-based testing framework
    # ════════════════════════════════════════════════════════════════════════════
    RAPIDCHECK_STATIC_LIB = "${libPath s.rapidcheck-static}/lib/librapidcheck.a"
    RAPIDCHECK_INCLUDE = "${devPath s.rapidcheck-static}/include"

    # ════════════════════════════════════════════════════════════════════════════
    # boost - C++ libraries (used heavily by upstream nix)
    # ════════════════════════════════════════════════════════════════════════════
    BOOST_LIB_DIR = "${libPath s.boost-static}/lib"
    BOOST_INCLUDE = "${devPath s.boost-static}/include"

    # ════════════════════════════════════════════════════════════════════════════
    # brotli - compression
    # ════════════════════════════════════════════════════════════════════════════
    BROTLI_COMMON_LIB = "${libPath s.brotli-static}/lib/libbrotlicommon.a"
    BROTLI_DEC_LIB = "${libPath s.brotli-static}/lib/libbrotlidec.a"
    BROTLI_ENC_LIB = "${libPath s.brotli-static}/lib/libbrotlienc.a"
    BROTLI_INCLUDE = "${devPath s.brotli-static}/include"

    # ════════════════════════════════════════════════════════════════════════════
    # libsodium - cryptography
    # ════════════════════════════════════════════════════════════════════════════
    LIBSODIUM_STATIC_LIB = "${libPath s.libsodium-static}/lib/libsodium.a"
    LIBSODIUM_INCLUDE = "${devPath s.libsodium-static}/include"

    # ════════════════════════════════════════════════════════════════════════════
    # libarchive - archive handling
    # ════════════════════════════════════════════════════════════════════════════
    LIBARCHIVE_STATIC_LIB = "${libPath s.libarchive-static}/lib/libarchive.a"
    LIBARCHIVE_INCLUDE = "${devPath s.libarchive-static}/include"

    # ════════════════════════════════════════════════════════════════════════════
    # binaryen - NOW BUILT WITH BUCK2 (vendor/binaryen/BUCK)
    # Avoids glibc __isoc23_* symbols that are incompatible with musl
    # ════════════════════════════════════════════════════════════════════════════

    # ════════════════════════════════════════════════════════════════════════════
    # wasmtime - WebAssembly runtime (pre-built C API)
    # ════════════════════════════════════════════════════════════════════════════
    # Note: Static linking requires additional system libs: -lpthread -ldl -lm
    WASMTIME_STATIC_LIB = "${s.wasmtime-c-api}/lib/libwasmtime.a"
    WASMTIME_INCLUDE = "${s.wasmtime-c-api}/include"

    # ════════════════════════════════════════════════════════════════════════════
    # mimalloc - fast allocator (replaces musl malloc, reduces lock contention)
    # ════════════════════════════════════════════════════════════════════════════
    MIMALLOC_STATIC_LIB = "${libPath s.mimalloc-static}/lib/libmimalloc.a"
    MIMALLOC_INCLUDE = "${devPath s.mimalloc-static}/include"
  '';
in
pkgs.writeText "nix-deps.bzl" content
