# nix/gen-buck-deps.nix
#
# Generates a Starlark file with Nix store paths for prebuilt_cxx_library.
# This avoids symlinks that break when store paths change.
#
# Usage: nix-build nix/gen-buck-deps.nix -o third_party/nix-deps.bzl
#
# The generated file contains variable assignments for each static library's
# paths. These are imported in third_party/BUCK and used with nix_prebuilt_cxx_library.
#
{
  pkgs ? import <nixpkgs> { },
}:
let
  deps = import ./deps.nix { inherit pkgs; };
  s = deps.static;

  # Helper to get lib path (handles multi-output derivations)
  libPath = pkg: pkg.out or pkg;
  devPath = pkg: pkg.dev or pkg;

  # Generate the .bzl content
  content = ''
    # AUTO-GENERATED by nix/gen-buck-deps.nix
    # Do not edit manually. Regenerate with:
    #   nix-build nix/gen-buck-deps.nix -o third_party/nix-deps.bzl
    #
    # Nix store paths for static libraries (musl, no glibc).
    # Used by nix_prebuilt_cxx_library() in third_party/BUCK.

    # ════════════════════════════════════════════════════════════════════════════
    # BLAKE3 - fast cryptographic hash
    # ════════════════════════════════════════════════════════════════════════════
    # TODO[b7r6]: confirm TBB performance improvement
    BLAKE3_STATIC_LIB = "${libPath s.blake3-static}/lib/libblake3.a"
    BLAKE3_INCLUDE = "${devPath s.blake3-static}/include"

    # ════════════════════════════════════════════════════════════════════════════
    # LibreSSL - TLS/crypto (no OpenSSL)
    # ════════════════════════════════════════════════════════════════════════════
    LIBRESSL_CRYPTO_LIB = "${libPath s.libressl-static}/lib/libcrypto.a"
    LIBRESSL_SSL_LIB = "${libPath s.libressl-static}/lib/libssl.a"
    LIBRESSL_TLS_LIB = "${libPath s.libressl-static}/lib/libtls.a"
    LIBRESSL_INCLUDE = "${devPath s.libressl-static}/include"

    # ════════════════════════════════════════════════════════════════════════════
    # ada - WHATWG URL parser
    # ════════════════════════════════════════════════════════════════════════════
    ADA_STATIC_LIB = "${libPath s.ada-static}/lib/libada.a"
    ADA_INCLUDE = "${libPath s.ada-static}/include"

    # ════════════════════════════════════════════════════════════════════════════
    # RE2 - fast regex
    # ════════════════════════════════════════════════════════════════════════════
    RE2_STATIC_LIB = "${libPath s.re2-static}/lib/libre2.a"
    RE2_INCLUDE = "${devPath s.re2-static}/include"

    # ════════════════════════════════════════════════════════════════════════════
    # Catch2 - testing framework
    # ════════════════════════════════════════════════════════════════════════════
    CATCH2_STATIC_LIB = "${libPath s.catch2-static}/lib/libCatch2.a"
    CATCH2_MAIN_LIB = "${libPath s.catch2-static}/lib/libCatch2Main.a"
    CATCH2_INCLUDE = "${devPath s.catch2-static}/include"

    # ════════════════════════════════════════════════════════════════════════════
    # nanobench - microbenchmark framework
    # ════════════════════════════════════════════════════════════════════════════
    NANOBENCH_STATIC_LIB = "${libPath s.nanobench-static}/lib/libnanobench.a"
    NANOBENCH_INCLUDE = "${libPath s.nanobench-static}/include"

    # ════════════════════════════════════════════════════════════════════════════
    # rapidcheck - property-based testing framework
    # ════════════════════════════════════════════════════════════════════════════
    RAPIDCHECK_STATIC_LIB = "${libPath s.rapidcheck-static}/lib/librapidcheck.a"
    RAPIDCHECK_INCLUDE = "${devPath s.rapidcheck-static}/include"

    # ════════════════════════════════════════════════════════════════════════════
    # binaryen - WebAssembly compiler infrastructure
    # ════════════════════════════════════════════════════════════════════════════
    BINARYEN_STATIC_LIB = "${libPath s.binaryen-static}/lib/libbinaryen.a"
    BINARYEN_INCLUDE = "${libPath s.binaryen-static}/include"
  '';
in
pkgs.writeText "nix-deps.bzl" content
