# straylight // nix // fetchers // tests

cxx_test(
    name = "github_test",
    srcs = ["github_test.cpp"],
    deps = [
        "//src/nix/tests:test_utils",
        "//src/nix/fetchers:fetchers",
        "//src/nix/util:util",
    ],
    compiler_flags = ["-std=c++23"],
    linker_flags = ["-lpthread"],
    link_style = "static",
)
