# src/straylight/test/unit/cli/BUCK

cxx_test(
    name = "args_test",
    srcs = ["args_test.cpp"],
    deps = [
        "//src/straylight/nix/cli:args",
        "//vendor:catch2",
    ],
    compiler_flags = ["-std=c++23"],
    link_style = "static",
)
