# src/straylight/test/unit/adapters/BUCK

cxx_test(
    name = "nix_strings_adapter_test",
    srcs = ["nix_strings_adapter_test.cpp"],
    deps = [
        "//src/straylight/nix/adapters:nix_strings_adapter",
        "//vendor:catch2",
        "//vendor:rapidcheck",
    ],
    compiler_flags = ["-std=c++23"],
    link_style = "static",
)

cxx_test(
    name = "eval_adapter_test",
    srcs = ["eval_adapter_test.cpp"],
    deps = [
        "//src/straylight/nix/adapters:eval_adapter",
        "//vendor:catch2",
    ],
    compiler_flags = ["-std=c++23"],
    link_style = "static",
)

cxx_test(
    name = "store_adapter_test",
    srcs = ["store_adapter_test.cpp"],
    deps = [
        "//src/straylight/nix/store:two_tier_store",
        "//src/straylight/nix/testing:testing",
        "//vendor:catch2",
    ],
    compiler_flags = ["-std=c++23"],
    link_style = "static",
)
