# src/straylight/test/unit/data/BUCK

cxx_test(
    name = "chunked_vector_test",
    srcs = ["chunked_vector_test.cpp"],
    deps = [
        "//src/straylight/nix/data:chunked_vector",
        "//vendor:catch2",
        "//vendor:rapidcheck",
    ],
    compiler_flags = ["-std=c++23"],
    link_style = "static",
)

cxx_test(
    name = "lru_cache_test",
    srcs = ["lru_cache_test.cpp"],
    deps = [
        "//src/straylight/nix/data:lru_cache",
        "//vendor:catch2",
        "//vendor:rapidcheck",
    ],
    compiler_flags = ["-std=c++23"],
    link_style = "static",
)

# DISABLED: std::span conversion errors and API mismatches
# cxx_test(
#     name = "serialise_test",
#     srcs = ["serialise_test.cpp"],
#     deps = [
#         "//src/straylight/nix/data:serialise",
#         "//vendor:catch2",
#         "//vendor:rapidcheck",
#     ],
#     compiler_flags = ["-std=c++23"],
#     link_style = "static",
# )

cxx_test(
    name = "topo_sort_test",
    srcs = ["topo_sort_test.cpp"],
    deps = [
        "//src/straylight/nix/data:topo_sort",
        "//vendor:catch2",
        "//vendor:rapidcheck",
    ],
    compiler_flags = ["-std=c++23"],
    link_style = "static",
)
