cxx_binary(
    name = "bench_evring",
    srcs = ["bench_evring.cpp"],
    compiler_flags = ["-std=c++23", "-O3"],
    deps = [
        "//src/straylight/evring:evring",
    ],
    link_style = "static",
)
